@echo off
echo Creating folder structure...

mkdir main.jsx App.jsx index.css styles lib contexts hooks services routes layouts components\ui components\layout components\home components\blog components\blog-details components\books components\book-details components\reader components\ai components\dashboard\common components\dashboard\blogger components\dashboard\author components\dashboard\reader components\dashboard\admin components\profile components\settings components\modals pages\public pages\auth pages\home pages\blog pages\books pages\reader pages\search pages\dashboard pages\profile pages\settings pages\error 2>nul

echo Creating files...

type nul > main.jsx
type nul > App.jsx
type nul > index.css
type nul > styles\theme.css
type nul > lib\axios.js
type nul > lib\utils.js
type nul > lib\constants.js
type nul > lib\validators.js
type nul > contexts\AuthContext.jsx
type nul > contexts\ThemeContext.jsx
type nul > contexts\NotificationContext.jsx
type nul > hooks\useAuth.js
type nul > hooks\useLocalStorage.js
type nul > hooks\useDebounce.js
type nul > hooks\useInfiniteScroll.js
type nul > hooks\useDocumentTitle.js
type nul > services\authService.js
type nul > services\blogService.js
type nul > services\bookService.js
type nul > services\userService.js
type nul > services\aiService.js
type nul > services\analyticsService.js
type nul > services\paymentService.js
type nul > routes\AppRoutes.jsx
type nul > routes\PrivateRoute.jsx
type nul > routes\RoleBasedRoute.jsx
type nul > routes\PublicRoute.jsx
type nul > layouts\RootLayout.jsx
type nul > layouts\DashboardLayout.jsx
type nul > layouts\AuthLayout.jsx
type nul > layouts\BlankLayout.jsx
type nul > components\ui\Button.jsx
type nul > components\ui\Input.jsx
type nul > components\ui\Textarea.jsx
type nul > components\ui\Select.jsx
type nul > components\ui\Checkbox.jsx
type nul > components\ui\Radio.jsx
type nul > components\ui\Toggle.jsx
type nul > components\ui\Modal.jsx
type nul > components\ui\Drawer.jsx
type nul > components\ui\Dropdown.jsx
type nul > components\ui\Tabs.jsx
type nul > components\ui\Accordion.jsx
type nul > components\ui\Tooltip.jsx
type nul > components\ui\Toast.jsx
type nul > components\ui\Skeleton.jsx
type nul > components\ui\Spinner.jsx
type nul > components\ui\Avatar.jsx
type nul > components\ui\Badge.jsx
type nul > components\ui\Card.jsx
type nul > components\ui\Breadcrumb.jsx
type nul > components\ui\Pagination.jsx
type nul > components\ui\RatingStars.jsx
type nul > components\ui\ProgressBar.jsx
type nul > components\ui\SearchBar.jsx
type nul > components\ui\FileUploader.jsx
type nul > components\ui\ImageCropper.jsx
type nul > components\ui\RichTextEditor.jsx
type nul > components\layout\Navbar.jsx
type nul > components\layout\NavbarDesktop.jsx
type nul > components\layout\NavbarMobile.jsx
type nul > components\layout\Sidebar.jsx
type nul > components\layout\Footer.jsx
type nul > components\layout\Header.jsx
type nul > components\layout\Breadcrumbs.jsx
type nul > components\home\HeroSection.jsx
type nul > components\home\FeaturedBlogs.jsx
type nul > components\home\FeaturedBooks.jsx
type nul > components\home\TrendingSection.jsx
type nul > components\home\CategoriesSection.jsx
type nul > components\home\TopAuthors.jsx
type nul > components\home\NewsletterSignup.jsx
type nul > components\home\CTASection.jsx
type nul > components\blog\BlogCard.jsx
type nul > components\blog\BlogGrid.jsx
type nul > components\blog\BlogList.jsx
type nul > components\blog\BlogSidebar.jsx
type nul > components\blog\BlogFilters.jsx
type nul > components\blog\BlogSearch.jsx
type nul > components\blog\FeaturedBlogCard.jsx
type nul > components\blog\BlogSkeleton.jsx
type nul > components\blog-details\BlogHeader.jsx
type nul > components\blog-details\BlogContent.jsx
type nul > components\blog-details\BlogAuthorCard.jsx
type nul > components\blog-details\BlogComments.jsx
type nul > components\blog-details\CommentForm.jsx
type nul > components\blog-details\CommentItem.jsx
type nul > components\blog-details\RelatedBlogs.jsx
type nul > components\blog-details\BlogActions.jsx
type nul > components\blog-details\TableOfContents.jsx
type nul > components\books\BookCard.jsx
type nul > components\books\BookGrid.jsx
type nul > components\books\BookList.jsx
type nul > components\books\BookFilters.jsx
type nul > components\books\BookSearch.jsx
type nul > components\books\GenreCloud.jsx
type nul > components\books\BookSkeleton.jsx
type nul > components\book-details\BookHeader.jsx
type nul > components\book-details\BookCover.jsx
type nul > components\book-details\BookInfo.jsx
type nul > components\book-details\BookDescription.jsx
type nul > components\book-details\BookActions.jsx
type nul > components\book-details\BookReviews.jsx
type nul > components\book-details\ReviewForm.jsx
type nul > components\book-details\ReviewItem.jsx
type nul > components\book-details\AuthorBooks.jsx
type nul > components\book-details\SimilarBooks.jsx
type nul > components\reader\PDFViewer.jsx
type nul > components\reader\EpubReader.jsx
type nul > components\reader\ReadingProgress.jsx
type nul > components\reader\ReaderControls.jsx
type nul > components\reader\FontSettings.jsx
type nul > components\reader\HighlightSidebar.jsx
type nul > components\ai\AIAssistantDrawer.jsx
type nul > components\ai\AIGenerator.jsx
type nul > components\ai\AIGrammarChecker.jsx
type nul > components\ai\AITitleGenerator.jsx
type nul > components\ai\AISEOOptimizer.jsx
type nul > components\ai\AIBookOutline.jsx
type nul > components\ai\AIResearchAssistant.jsx
type nul > components\ai\AISummarizer.jsx
type nul > components\ai\AIChatInterface.jsx
type nul > components\dashboard\common\StatsCard.jsx
type nul > components\dashboard\common\ChartCard.jsx
type nul > components\dashboard\common\DataTable.jsx
type nul > components\dashboard\common\ActivityFeed.jsx
type nul > components\dashboard\common\NotificationItem.jsx
type nul > components\dashboard\common\QuickActions.jsx
type nul > components\dashboard\blogger\BloggerDashboard.jsx
type nul > components\dashboard\blogger\BlogStats.jsx
type nul > components\dashboard\blogger\RecentPosts.jsx
type nul > components\dashboard\blogger\PostAnalytics.jsx
type nul > components\dashboard\blogger\CreatePostForm.jsx
type nul > components\dashboard\blogger\EditPostForm.jsx
type nul > components\dashboard\blogger\PostsTable.jsx
type nul > components\dashboard\blogger\DraftsList.jsx
type nul > components\dashboard\blogger\ScheduledPosts.jsx
type nul > components\dashboard\blogger\SEOForm.jsx
type nul > components\dashboard\author\AuthorDashboard.jsx
type nul > components\dashboard\author\BookStats.jsx
type nul > components\dashboard\author\UploadBookForm.jsx
type nul > components\dashboard\author\EditBookForm.jsx
type nul > components\dashboard\author\BooksTable.jsx
type nul > components\dashboard\author\DownloadAnalytics.jsx
type nul > components\dashboard\author\RoyaltyTracker.jsx
type nul > components\dashboard\author\ReviewModeration.jsx
type nul > components\dashboard\reader\ReaderDashboard.jsx
type nul > components\dashboard\reader\ReadingHistory.jsx
type nul > components\dashboard\reader\BookmarkedBlogs.jsx
type nul > components\dashboard\reader\BookmarkedBooks.jsx
type nul > components\dashboard\reader\FollowedCreators.jsx
type nul > components\dashboard\reader\RecentlyViewed.jsx
type nul > components\dashboard\reader\ReadingStreak.jsx
type nul > components\dashboard\reader\BadgesCollection.jsx
type nul > components\dashboard\reader\PersonalizedRecommendations.jsx
type nul > components\dashboard\admin\AdminDashboard.jsx
type nul > components\dashboard\admin\UsersTable.jsx
type nul > components\dashboard\admin\UserDetailModal.jsx
type nul > components\dashboard\admin\RoleApprovalQueue.jsx
type nul > components\dashboard\admin\BlogsModeration.jsx
type nul > components\dashboard\admin\BooksModeration.jsx
type nul > components\dashboard\admin\ReportedContent.jsx
type nul > components\dashboard\admin\PlatformAnalytics.jsx
type nul > components\dashboard\admin\RevenueDashboard.jsx
type nul > components\dashboard\admin\SubscriptionsManager.jsx
type nul > components\dashboard\admin\SystemSettings.jsx
type nul > components\dashboard\admin\NotificationBroadcast.jsx
type nul > components\dashboard\admin\ActivityLogs.jsx
type nul > components\profile\PublicProfile.jsx
type nul > components\profile\ProfileHeader.jsx
type nul > components\profile\ProfileTabs.jsx
type nul > components\profile\UserBlogs.jsx
type nul > components\profile\UserBooks.jsx
type nul > components\profile\FollowersList.jsx
type nul > components\profile\FollowingList.jsx
type nul > components\profile\ProfileSkeleton.jsx
type nul > components\settings\SettingsLayout.jsx
type nul > components\settings\AccountSettings.jsx
type nul > components\settings\ProfileSettings.jsx
type nul > components\settings\SecuritySettings.jsx
type nul > components\settings\NotificationSettings.jsx
type nul > components\settings\PrivacySettings.jsx
type nul > components\settings\SubscriptionSettings.jsx
type nul > components\settings\RoleRequestForm.jsx
type nul > components\settings\DeleteAccountModal.jsx
type nul > components\settings\PreferencesSettings.jsx
type nul > components\modals\LoginModal.jsx
type nul > components\modals\RegisterModal.jsx
type nul > components\modals\ForgotPasswordModal.jsx
type nul > components\modals\ShareModal.jsx
type nul > components\modals\ReportModal.jsx
type nul > components\modals\ConfirmModal.jsx
type nul > pages\public\LandingPage.jsx
type nul > pages\public\AboutPage.jsx
type nul > pages\public\ContactPage.jsx
type nul > pages\public\PricingPage.jsx
type nul > pages\public\FAQPage.jsx
type nul > pages\public\TermsPage.jsx
type nul > pages\public\PrivacyPage.jsx
type nul > pages\public\CareersPage.jsx
type nul > pages\public\BlogArchive.jsx
type nul > pages\auth\LoginPage.jsx
type nul > pages\auth\RegisterPage.jsx
type nul > pages\auth\ForgotPasswordPage.jsx
type nul > pages\auth\ResetPasswordPage.jsx
type nul > pages\auth\VerifyEmailPage.jsx
type nul > pages\auth\ChooseRolePage.jsx
type nul > pages\home\HomePage.jsx
type nul > pages\blog\BlogsPage.jsx
type nul > pages\blog\BlogDetailPage.jsx
type nul > pages\blog\CategoryPage.jsx
type nul > pages\blog\TagPage.jsx
type nul > pages\books\BooksPage.jsx
type nul > pages\books\BookDetailPage.jsx
type nul > pages\books\GenrePage.jsx
type nul > pages\reader\ReadBookPage.jsx
type nul > pages\reader\ReadingHistoryPage.jsx
type nul > pages\search\SearchResultsPage.jsx
type nul > pages\dashboard\BloggerDashboardPage.jsx
type nul > pages\dashboard\AuthorDashboardPage.jsx
type nul > pages\dashboard\ReaderDashboardPage.jsx
type nul > pages\dashboard\AdminDashboardPage.jsx
type nul > pages\profile\ProfilePage.jsx
type nul > pages\profile\MyProfilePage.jsx
type nul > pages\settings\SettingsPage.jsx
type nul > pages\error\NotFoundPage.jsx
type nul > pages\error\UnauthorizedPage.jsx
type nul > pages\error\ServerErrorPage.jsx

echo Done! File structure created successfully.